### ISSUE TITLE
HTML Layout

### ISSUE THREAD

**Issue by jciii91** [jciii91/space-launch#1]

**Comment by Asafran92** [comment]
Initial HTML added. 
Based on the wireframe

1. We will hold the calendar and the user searches within the header tag wrapped in a div element
2. I created each of the inputs which will populate based off of a user search. 
3. I think we should only create one input type and have the rest dynamically created via Javascript. Once Hilary creates classes we can work on that
4. Two divs wrapped in main. One representing the map and the other the launch info

**Comment by Asafran92** [comment]
Added stylesheet and javascript CDN's for materialize
