### ISSUE TITLE
Space API

### ISSUE THREAD

**Issue by jciii91** [jciii91/space-launch#5]

**Comment by Asafran92** [comment]
Base URL: ll.thespacedevs.com/2.2.0
Think we should discuss which parameters we are looking for. What I have so far:
1. rocket__spacecraftflight__spacecraft__name
2. results
  a. slug
  b. status
3. Mission
   a. description
4. Pad
   a. latitude
   b. longitude
   c. name
5. Window Start

**Comment by jciii91** [comment]
These look fine. I'll look through the endpoint and see if there are others I think should be added but if this is everything we use I think that's plenty.
